### ISSUE TITLE
Twitter for Android Detection

### ISSUE THREAD

**Issue by azaremba-adsterra** [51Degrees/data-issues#2]
For the latest bases I found that there is a strange behaviour in detection of Twitter for Android (around from 28/29-04-2024).
If send such hints - fodegrees detect as **Chrome Mobile** without **Twitter for Android**  :(
`
				"User-Agent":                  "Mozilla/5.0 (Linux; Android 13; RMX3762 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.106 Mobile Safari/537.36 TwitterAndroid",
				"Sec-CH-UA":                   "\"Chromium\";v=\"122\", \"Not(A:Brand\";v=\"24\", \"Android WebView\";v=\"122\"",
				"Sec-CH-UA-Full-Version":      "\"122.0.6261.106\"",
				"Sec-CH-UA-Full-Version-List": "\"Chromium\";v=\"122.0.6261.106\", \"Not(A:Brand\";v=\"24.0.0.0\", \"Android WebView\";v=\"122.0.6261.106\"",
				"Sec-CH-UA-Mobile":            "?1",
				"Sec-CH-UA-Model":             "\"RMX3762\"",
				"Sec-CH-UA-Platform":          "\"Android\"",
				"Sec-CH-UA-Platform-Version":  "\"13.0.0\"",
`
But if you remove "Sec-CH-UA-Platform-Version" hint  - it  works!

**Comment by Tracy51D** [comment]
Hi there

We have done some testing on both the User-Agent as well as the User-Agent Client Hints.
When you use the User-Agent only it does show ‘Twitter for Android’ correctly.
When you use the User-Agent together with the Client Hints it also shows correctly. This is the case when ‘Sec-CH-UA-Platform-Version’ is excluded as well.

Below are links to our User-Agent tester page which shows the above: (apologies for the long links, GH seems to be playing up for me today)

- Using the [User-Agent only](https://51degrees.com/developers/user-agent-tester?headers=User-Agent%3A+Mozilla%2F5.0+(Linux%3B+Android+13%3B+RMX3762+Build%2FTP1A.220624.014%3B+wv)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Version%2F4.0+Chrome%2F122.0.6261.106+Mobile+Safari%2F537.36+TwitterAndroid%0D%0A)
- Using both User-Agent and the full list of Client Hints - [UACH](https://51degrees.com/developers/user-agent-tester?headers=User-Agent%3A+Mozilla%2F5.0+(Linux%3B+Android+13%3B+RMX3762+Build%2FTP1A.220624.014%3B+wv)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Version%2F4.0+Chrome%2F122.0.6261.106+Mobile+Safari%2F537.36+TwitterAndroid%0D%0ASec-CH-UA%3A+%22Chromium%22%3Bv%3D%22122%22%2C+%22Not(A%3ABrand%22%3Bv%3D%2224%22%2C+%22Android+WebView%22%3Bv%3D%22122%22%0D%0ASec-CH-UA-Full-Version%3A+%22122.0.6261.106%22+%0D%0ASec-CH-UA-Full-Version-List%3A+%22Chromium%22%3Bv%3D%22122.0.6261.106%22%2C%22Not(A%3ABrand%22%3Bv%3D%2224.0.0.0%22%2C+%22Android+WebView%22%3Bv%3D%22122.0.6261.106%22+%0D%0ASec-CH-UA-Mobile%3A+%22%3F1%22%0D%0ASec-CH-UA-Model%3A+%22RMX3762%22%0D%0ASec-CH-UA-Platform%3A+%22Android%22%0D%0ASec-CH-UA-Platform-Version%3A+%2213.0.0%22%0D%0A)
- Using [User-Agent and Client Hints (not including “Sec-CH-UA-Platform-Version”)](https://51degrees.com/developers/user-agent-tester?headers=User-Agent%3A+Mozilla%2F5.0+(Linux%3B+Android+13%3B+RMX3762+Build%2FTP1A.220624.014%3B+wv)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Version%2F4.0+Chrome%2F122.0.6261.106+Mobile+Safari%2F537.36+TwitterAndroid%0D%0ASec-CH-UA%3A+%22Chromium%22%3Bv%3D%22122%22%2C+%22Not(A%3ABrand%22%3Bv%3D%2224%22%2C+%22Android+WebView%22%3Bv%3D%22122%22%0D%0ASec-CH-UA-Full-Version%3A+%22122.0.6261.106%22+%0D%0ASec-CH-UA-Full-Version-List%3A+%22Chromium%22%3Bv%3D%22122.0.6261.106%22%2C%22Not(A%3ABrand%22%3Bv%3D%2224.0.0.0%22%2C+%22Android+WebView%22%3Bv%3D%22122.0.6261.106%22+%0D%0ASec-CH-UA-Mobile%3A+%22%3F1%22%0D%0ASec-CH-UA-Model%3A+%22RMX3762%22%0D%0ASec-CH-UA-Platform%3A+%22Android%22%0D%0A%0D%0A)

Is this the only time you’ve seen this issue, or are there other instances of this that you’ve seen?

Thanks
Tracy

**Comment by barbiedrummer** [comment]
Hi, @Tracy51D!

I've made some screenshots to save the results:

* Using the User-Agent only (detects twitter)
![image](https://github.com/51Degrees/data-issues/assets/17202065/c00bf59a-1b0d-49ff-a878-590bfe00ba4e)
* Using both User-Agent and the full list of Client Hints - UACH (does not detect twitter)
![image](https://github.com/51Degrees/data-issues/assets/17202065/1eb27847-7885-47f3-a508-330a8c5a01a9)
* Using User-Agent and Client Hints (not including “Sec-CH-UA-Platform-Version”) (does not detect twitter)
![image](https://github.com/51Degrees/data-issues/assets/17202065/00e6a58b-6df7-4f26-b0e6-544f2bd9b653)

The main problem is detection of Twitter in general. When Twitter also sends CH-headers, the detection is less accurate compared to using only the UA-header.

The problem looks the same as described in https://github.com/51Degrees/device-detection-go/issues/9 (Facebook Browser)

**Comment by Tracy51D** [comment]
Thanks for providing screenshots. It looks like the detection has changed since I last sent the links on 4 April.
It seems to be an algorithm problem, so would require engineering work on our side to investigate.

Thank you for raising this, I will speak with the relevant team.

Tracy

**Comment by Tracy51D** [comment]
Hi there,

In recent months we've been adjusting how we detect User-Agent Client Hint headers, and part of that work included tweaks to the Sec-CH-UA-Full-Version-List header. As you've spotted, further adjustment in the detection is needed.

We are currently modifying this in the data. As soon as this change has been completed, I will be back in touch to confirm that all is working correctly.

Thank you for your patience in this matter.
Tracy

**Comment by Tracy51D** [comment]
Hi there,

This work has now been completed. I'm including the links to our User-Agent tester page for you to see:

- [User-Agent](https://51degrees.com/developers/user-agent-tester?headers=User-Agent%3A+Mozilla%2F5.0+(Linux%3B+Android+13%3B+RMX3762+Build%2FTP1A.220624.014%3B+wv)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Version%2F4.0+Chrome%2F122.0.6261.106+Mobile+Safari%2F537.36+TwitterAndroid%0D%0A) only

- [User-Agent Client Hints](https://51degrees.com/developers/user-agent-tester?headers=User-Agent%3A+Mozilla%2F5.0+(Linux%3B+Android+13%3B+RMX3762+Build%2FTP1A.220624.014%3B+wv)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Version%2F4.0+Chrome%2F122.0.6261.106+Mobile+Safari%2F537.36+TwitterAndroid+%0D%0ASec-CH-UA%3A+%22Chromium%22%3Bv%3D%22122%22%2C+%22Not(A%3ABrand%22%3Bv%3D%2224%22%2C+%22Android+WebView%22%3Bv%3D%22122%22+%0D%0ASec-CH-UA-Full-Version%3A+%22122.0.6261.106%22+%0D%0ASec-CH-UA-Full-Version-List%3A+%22Chromium%22%3Bv%3D%22122.0.6261.106%22%2C+%22Not(A%3ABrand%22%3Bv%3D%2224.0.0.0%22%2C+%22Android+WebView%22%3Bv%3D%22122.0.6261.106%22+%0D%0ASec-CH-UA-Mobile%3A+%3F1+%0D%0ASec-CH-UA-Model%3A+%22RMX3762%22%0D%0ASec-CH-UA-Platform%3A+%22Android%22+%0D%0ASec-CH-UA-Platform-Version%3A+%2213.0.0%22) - full version

Please can you confirm that this is now detecting correctly on your end.

Thanks
Tracy

**Comment by Tracy51D** [comment]
Hi there,

As mentioned previously this issue has been fixed. As I've not heard back from you I will consider this issue resolved and close the issue. If you have any further issues please do reach out.

Thanks
Tracy

**Comment by barbiedrummer** [comment]
> Please can you confirm that this is now detecting correctly on your end.

@Tracy51D Thanks for solving the problem. Now everything works correctly.
