### ISSUE TITLE
Incorrect PlatformVersion for Android devices on the last update

### ISSUE THREAD

**Issue by leonidboykov** [51Degrees/data-issues#3]
The last update (maybe since 2024-09-03) introduced an incorrect detection of PlatformVersion for a Chrome Mobile user agent. For example, the UA

```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
```

was detected as Android 10.0 on 2024-09-01, but this UA is now detected as Android Unknown. The problem relates to multiple Chrome Mobile versions: I've checked versions from 112 to 128.

**Comment by data51degrees** [comment]
@leonidboykov, thank you for your question.

As of the 2nd of September we have altered our approach to detecting reduced user-agents. Our detection will now return Android Unknown where a reduced user-agent is submitted without additional platform headers (i.e. Sec-CH-UA-Platform and Sec-CH-UA-Platform-Version). Previously, as you mentioned, we would identify such user-agents as Android 10.

We have made this change to align with Google's information around reduced user-agents. The 'Android 10; K' segment of a reduced user-agent is static and therefore the Android version is in many cases not accurate. 

The reduced user-agents here in the rollout plan show examples where the Android versions are not aligned. [https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-final-reduced-state:~:text=93.0.0.0%20Safari/537.36-,Sample%20UA%20Strings%3A%20Final%20Reduced%20State,-Desktop%20](url)

**Comment by leonidboykov** [comment]
@data51degrees thank you for the reply. Is it possible to provide some flags to enable the legacy behavior? Too many devices are now detected as Android Unknown and we need time to adapt.

**Comment by data51degrees** [comment]
@leonidboykov - Unfortunately it is not possible to enable this legacy behaviour in the new export file.

We suggest a couple of additional options for consideration:

- You could revert to an older version of the data file, disable updates temporarily, and adapt your code accordingly. Once the changes are made, you could re-enable updates.

- On the code level, where the data is received, you could implement a temporary workaround to automatically replace 'Android Unknown' with 'Android 10.0'.

Additionally, we recommend that you include the Client Hint headers "sec-ch-ua-platform" and "sec-ch-ua-platform-version" (and others) as part of the evidence used for device detection. This will allow for accurate detection of the actual Android version. With only the redacted User-Agent string, the detection might result in an incorrect Android 10.0 version, so having "Android Unknown" at least reflects the uncertainty of the version.

For further documentation on User-Agent Client Hints you can refer [here](https://51degrees.com/documentation/4.4/_device_detection__features__u_a_c_h__overview.html).

**Comment by leonidboykov** [comment]
Thanks for the reply, @data51degrees! By the way, are you posting changelogs or upcoming changes somewhere?

**Comment by data51degrees** [comment]
@leonidboykov – Updates and new features related to the Data team are generally posted via our 51Degrees
[blog](https://51degrees.com/resources/blogs) page as well as through customer communications (as long as you’ve opted into receiving these emails 😊)
